// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculosSanJoaquinMVC.Models.DAL;

namespace VehiculosSanJoaquinMVC.Migrations
{
    [DbContext(typeof(DbContextVehiculoSanJoaquin))]
    partial class DbContextVehiculoSanJoaquinModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehiculosSanJoaquinMVC.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("ClId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(30)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClApellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("ClApellido2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClCedula")
                        .HasColumnType("int");

                    b.Property<string>("ClCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClNombre1")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("ClNombre2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClTelefono1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClTelefono2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClId");

                    b.ToTable("NS_tblClientes");
                });

            modelBuilder.Entity("VehiculosSanJoaquinMVC.Models.Entities.Listas", b =>
                {
                    b.Property<int>("LiCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LiActivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("LiCodigoPadre")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("LiNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("LiCodigo");

                    b.ToTable("NS_tblListas");
                });

            modelBuilder.Entity("VehiculosSanJoaquinMVC.Models.Entities.ListasDetalle", b =>
                {
                    b.Property<int>("LdClave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteClId")
                        .HasColumnType("int");

                    b.Property<int>("LdActivoV1")
                        .HasColumnType("int");

                    b.Property<string>("LdAplicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdDescripcion1")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("LdDescripcion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LdFecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LdFechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("LdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("LdusuarioCambio")
                        .HasColumnType("int");

                    b.Property<int>("LiCodigo")
                        .HasColumnType("int");

                    b.Property<int?>("ListasLiCodigo")
                        .HasColumnType("int");

                    b.HasKey("LdClave");

                    b.HasIndex("ClienteClId");

                    b.HasIndex("ListasLiCodigo");

                    b.ToTable("NS_tblListasDetalle");
                });

            modelBuilder.Entity("VehiculosSanJoaquinMVC.Models.Entities.ListasDetalle", b =>
                {
                    b.HasOne("VehiculosSanJoaquinMVC.Models.Entities.Cliente", "Cliente")
                        .WithMany("DetalleListas")
                        .HasForeignKey("ClienteClId");

                    b.HasOne("VehiculosSanJoaquinMVC.Models.Entities.Listas", "Listas")
                        .WithMany("DetalleListas")
                        .HasForeignKey("ListasLiCodigo");
                });
#pragma warning restore 612, 618
        }
    }
}
